export * from '../pages/Home/Carrousel/Carrousel';
export * from '../pages/Home/Carrousel/CarrouselRender';
export * from '../pages/Home/Carrousel/style';
export { default as Modal } from './Modal/Modal';
export * from './Modal/styles';
export * from '../pages/Detail/CastList/CastList';
export * from '../pages/Detail/CastList/style';
export * from './MoviesCard/MoviesCard';
export * from './MoviesCard/style';
export * from './Header/HeroSlide';
export { default as Navbar } from './Header/Navbar';
export * from './Header/style';
